apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-push
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-workflow
  dependencies:
    - name: new-commit
      eventSourceName: github
      eventName: git-push
      filters:
        data:
          - path: headers.X-Github-Event
            type: string
            value:
              - push
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: pipeline-build-
                namespace: argo
              spec:
                serviceAccountName: argo-workflow
                entrypoint: pipeline-build
                arguments:
                  parameters:
                    - name: repo_url
                    - name: revision
                volumes:
                  - name: workspace
                    emptyDir: {}
                  - name: podman-lib
                    emptyDir: {}
                templates:
                  - name: pipeline-build
                    dag:
                      tasks:
                        - name: build-operation
                          templateRef:
                            name: build-template
                            template: java-build
                            clusterScope: true
                          arguments:
                            parameters:
                              - name: repo_url
                                value: "{{workflow.parameters.repo_url}}"
                              - name: revision
                                value: "{{workflow.parameters.revision}}"
          parameters:
            - src:
                dependencyName: new-commit
                dataKey: body.repository.clone_url
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: new-commit
                dataKey: body.repository.master_branch
              dest: spec.arguments.parameters.1.value
