apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: build-template
spec:
  templates:
  - name: java-build
    dag:
      tasks:
        - name: clone
          templateRef:
            name: git-clone-template
            template: git-clone
            clusterScope: true
          arguments:
            parameters:
              - name: repo_url
                value: "{{workflow.parameters.repo_url}}"
              - name: revision
                value: "{{workflow.parameters.revision}}"
        - name: test-coverage
          dependencies: [clone]
          templateRef:
            name: test-coverage-templates
            template: gradle-test-coverage
            clusterScope: true
          arguments:
            parameters:
              - name: project_dir
                value: "{{tasks.clone.outputs.parameters.project_dir}}"
            artifacts:
              - name: clone
                from: "{{tasks.clone.outputs.artifacts.repo}}"
        - name: security-check
          dependencies: [clone]
          templateRef:
            name: security-check-templates
            template: trivy-scan
            clusterScope: true
          arguments:
            parameters:
              - name: project_dir
                value: "{{tasks.clone.outputs.parameters.project_dir}}"
            artifacts:
              - name: clone
                from: "{{tasks.clone.outputs.artifacts.repo}}"
        - name: final-artifact
          dependencies: [test-coverage, security-check]
          templateRef:
            name: final-artifact-templates
            template: podman-image
            clusterScope: true
          arguments:
            parameters:
              - name: image_name
                value: "{{tasks.clone.outputs.parameters.image_name}}"
              - name: image_tag
                value: "{{tasks.clone.outputs.parameters.image_tag}}"
              - name: project_dir
                value: "{{tasks.clone.outputs.parameters.project_dir}}"
            artifacts:
              - name: clone
                from: "{{tasks.clone.outputs.artifacts.repo}}"