apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: security-check-templates
spec:
  templates:
  - name: trivy-scan
    inputs:
      artifacts:
      - name: clone
        path: /workspace/repo
      parameters:
      - name: project_dir           
    container:
      image: aquasec/trivy:0.66.0
      workingDir: /workspace/repo
      volumeMounts:
        - name: workspace               
          mountPath: /workspace
      command: [sh, -euxc]
      args:
        - |
          trivy fs {{inputs.parameters.project_dir}} -f json -o results.json
    outputs:
      artifacts:
        - name: security-results
          path: /workspace/repo/results.json
